services:
  postgres:
    image: postgres:16-alpine
    container_name: roxiler-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: roxiler_db
    ports:
      - "5432:5432"
    volumes:
      - roxiler_pg_data:/var/lib/postgresql/data

volumes:
  roxiler_pg_data:
